updated queries.js in frontend to fix typos and add euery single cate…
vasylynash/alumn-space pull request #29
Opened 2021-09-04 18:47 UTC by melinamboedecker

…gory and label, updated mutation for ADD_USER with registerInput, and updated all comment body to commentText

2021-09-04 18:50 UTC, Zoneam approved these changes

2021-09-04 19:54 UTC, vasylynash requested changes

2021-09-04 19:54 UTC, vasylynash commented on client/src/utils/queries.js
> +//Can't include posts in single category search as posts aren't connected to the categories in typeDefs
Update typeDefs and check

2021-09-04 19:54 UTC, vasylynash commented on client/src/utils/queries.js
> +//Can't include posts in single category search as posts aren't connected to the categories in typeDefs
Update typeDefs and check

2021-09-05 03:06 UTC, melinamboedecker commented on client/src/utils/queries.js
> +//Can't include posts in single category search as posts aren't connected to the categories in typeDefs
going to check this with enum on a different branch

2021-09-05 03:06 UTC, melinamboedecker commented on client/src/utils/queries.js
> +//Can't include posts in single category search as posts aren't connected to the categories in typeDefs
going to check this with enum on a different branch

2021-09-05 03:07 UTC, closed without merging