added disabled fields to into and security tabs
vasylynash/alumn-space pull request #68
Opened 2021-09-13 19:36 UTC by Dimavich

2021-09-13 22:06 UTC, melinamboedecker requested changes
I made changes to the Info file that were merged with main (PR#64) and don't see them here, can you pull and merge with this branch?

2021-09-13 22:41 UTC, Zoneam approved these changes

2021-09-14 01:36 UTC, Zoneam approved these changes

2021-09-14 01:59 UTC, melinamboedecker approved these changes

2021-09-14 02:02 UTC, merged