added front end queries
vasylynash/alumn-space pull request #7
Opened 2021-08-31 05:41 UTC by melinamboedecker

2021-08-31 18:27 UTC, vasylynash approved these changes

2021-08-31 18:27 UTC, vasylynash commented on client/src/utils/queries.js
> +//For below query, do we need to put the posts in the Category typeDef?
I've added posts to category model. We'll see if it works

2021-08-31 18:27 UTC, vasylynash commented on client/src/utils/queries.js
> +//For below query, do we need to put the posts in the Label typeDef?
I've added posts to the label model. We'll see if it works

2021-08-31 18:28 UTC, vasylynash requested changes

2021-08-31 18:28 UTC, vasylynash commented on client/src/utils/queries.js
>  import { gql } from "@apollo/client";
We use single quotes for JS. Update please

2021-08-31 19:01 UTC, Dimavich approved these changes

2021-08-31 19:19 UTC, Zoneam approved these changes

2021-09-01 17:44 UTC, melinamboedecker commented on client/src/utils/queries.js
>  import { gql } from "@apollo/client";
Okay, done

2021-09-02 01:08 UTC, vasylynash approved these changes

2021-09-02 01:13 UTC, merged

2021-09-07 05:59 UTC, melinamboedecker commented
![](https://github.trello.services/images/mini-trello-icon.png) [front end react queries and mutations](https://trello.com/c/ebutCgrN/6-front-end-react-queries-and-mutations)