Profileinfopopulate
vasylynash/alumn-space pull request #79
Opened 2021-09-15 18:23 UTC by melinamboedecker

2021-09-15 18:28 UTC, vasylynash requested changes

2021-09-15 18:28 UTC, vasylynash commented on client/src/App.js
> +            {/* <Route exact path="/profile">
Duplicate? Remove

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/post/FullPost.js
> +    console.log('post ->     ', post)
Remove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/profile/Index.js
> +    console.log('index')
Remove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/profile/Index.js
> +        // variables: { id: '61400ff61f3834d48cc966d0' }
Remove

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/profile/Index.js
> +    console.log('data ->   ', data)
Remove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/profile/Security.js
> +    console.log('user ->     ', user)
Remove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/components/profile/UserPosts.js
> +    console.log('userposts')
REmove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/pages/Home.js
> +    console.log('HOME')
Remove console.log

2021-09-15 18:28 UTC, vasylynash commented on client/src/pages/Information.js
> +    // console.log('currentuser ->   ', currentUser)
REmove

2021-09-15 18:28 UTC, vasylynash commented on client/src/pages/Information.js
> +    // setFormState({
Remove

2021-09-15 18:28 UTC, vasylynash commented on client/src/pages/Profile.js
> +    console.log('profile')
Remove

2021-09-15 18:28 UTC, vasylynash commented on client/src/pages/Profile.js
> +        <UserProvider>
Are you using this?

2021-09-15 18:28 UTC, vasylynash commented on client/src/utils/UserContext.js
> +import React, { useState, useContext } from 'react';
Are you using UserProvider?

2021-09-15 19:02 UTC, melinamboedecker commented on client/src/utils/UserContext.js
> +import React, { useState, useContext } from 'react';
breaks if remove

2021-09-15 19:02 UTC, melinamboedecker commented on client/src/pages/Profile.js
> +        <UserProvider>
doesn't work if remove this tag

2021-09-15 19:02 UTC, melinamboedecker commented on client/src/pages/Profile.js
> +    console.log('profile')
removed

2021-09-15 19:02 UTC, melinamboedecker commented on client/src/pages/Information.js
> +    // setFormState({
removed file , wasn't using it

2021-09-15 19:03 UTC, melinamboedecker commented on client/src/pages/Information.js
> +    // console.log('currentuser ->   ', currentUser)
removed file

2021-09-15 19:03 UTC, melinamboedecker commented on client/src/components/profile/Index.js
> +    console.log('data ->   ', data)
removed

2021-09-15 19:04 UTC, melinamboedecker commented on client/src/components/profile/Index.js
> +        // variables: { id: '61400ff61f3834d48cc966d0' }
removed

2021-09-15 19:04 UTC, melinamboedecker commented on client/src/components/profile/Index.js
> +    console.log('index')
removed

2021-09-15 19:05 UTC, melinamboedecker commented on client/src/components/post/FullPost.js
> +    console.log('post ->     ', post)
removed

2021-09-15 19:07 UTC, melinamboedecker commented on client/src/App.js
> +            {/* <Route exact path="/profile">
removed

2021-09-15 19:15 UTC, vasylynash approved these changes

2021-09-15 19:15 UTC, Dimavich approved these changes

2021-09-15 19:18 UTC, merged

2021-09-25 14:59 UTC, melinamboedecker commented
![](https://github.trello.services/images/mini-trello-icon.png) [place for users to see current profile info or this can be pre-populated in the info page form fields.](https://trello.com/c/76kKFNuG/35-place-for-users-to-see-current-profile-info-or-this-can-be-pre-populated-in-the-info-page-form-fields)