Seeds
vasylynash/alumn-space pull request #9
Opened 2021-09-01 01:12 UTC by Zoneam

2021-09-01 16:01 UTC, vasylynash requested changes

2021-09-01 16:01 UTC, vasylynash commented on client/src/utils/API.js
> +// route to get logged in user's info (needs the token)
Why do we need this?

2021-09-01 16:01 UTC, vasylynash commented on server/seeders/postSeed.json
> +[
I've added changes to the model to include category and label. Can you update the seeds?

2021-09-01 19:28 UTC, Zoneam commented on client/src/utils/API.js
> +// route to get logged in user's info (needs the token)
we dont need this, I thought I removed it last time

2021-09-01 20:26 UTC, Dimavich approved these changes

2021-09-02 01:08 UTC, vasylynash approved these changes

2021-09-02 01:09 UTC, merged